// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"fmt"
	"time"
)

type ContactTypes string

const (
	ContactTypesInstagram ContactTypes = "instagram"
	ContactTypesFacebook  ContactTypes = "facebook"
	ContactTypesWhatsapp  ContactTypes = "whatsapp"
)

func (e *ContactTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContactTypes(s)
	case string:
		*e = ContactTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for ContactTypes: %T", src)
	}
	return nil
}

type Contact struct {
	UstadzID     int32        `json:"ustadzID"`
	ContactsType ContactTypes `json:"contactsType"`
	Value        string       `json:"value"`
}

type Event struct {
	ID        int32         `json:"id"`
	Name      string        `json:"name"`
	Venue     string        `json:"venue"`
	Masjid    sql.NullInt32 `json:"masjid"`
	Date      time.Time     `json:"date"`
	CreatedAt time.Time     `json:"createdAt"`
}

type EventsUstadz struct {
	EventID  int32 `json:"eventID"`
	UstadzID int32 `json:"ustadzID"`
}

type Masjid struct {
	ID         int32          `json:"id"`
	Name       string         `json:"name"`
	Address    string         `json:"address"`
	City       string         `json:"city"`
	Coordinate string         `json:"coordinate"`
	Logo       sql.NullString `json:"logo"`
	CreatedAt  time.Time      `json:"createdAt"`
}

type User struct {
	ID        int32          `json:"id"`
	Username  string         `json:"username"`
	Name      string         `json:"name"`
	Phone     int32          `json:"phone"`
	Gender    int32          `json:"gender"`
	Age       int32          `json:"age"`
	Avatar    sql.NullString `json:"avatar"`
	CreatedAt time.Time      `json:"createdAt"`
}

type UserEvent struct {
	UserID  int32 `json:"userID"`
	EventID int32 `json:"eventID"`
}

type UserFavoritedEvent struct {
	UserID  int32 `json:"userID"`
	EventID int32 `json:"eventID"`
}

type UserFavoritedMasjid struct {
	UserID   int32 `json:"userID"`
	MasjidID int32 `json:"masjidID"`
}

type UserFavoritedUstadz struct {
	UserID   int32 `json:"userID"`
	UstadzID int32 `json:"ustadzID"`
}

type Ustadz struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Avatar    sql.NullString `json:"avatar"`
	Gender    int32          `json:"gender"`
	CreatedAt time.Time      `json:"createdAt"`
}
