// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ChangePassword(ctx context.Context, arg ChangePasswordParams) (User, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateMasjid(ctx context.Context, arg CreateMasjidParams) (Masjid, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUstadz(ctx context.Context, arg CreateUstadzParams) (Ustadz, error)
	DeleteEvent(ctx context.Context, id int32) error
	DeleteMasjid(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	DeleteUstadz(ctx context.Context, id int32) error
	GetEvent(ctx context.Context, id int32) (Event, error)
	GetMasjid(ctx context.Context, id int32) (Masjid, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, phone string) (User, error)
	GetUstadz(ctx context.Context, id int32) (Ustadz, error)
	ListEvents(ctx context.Context) ([]Event, error)
	ListMasjids(ctx context.Context) ([]Masjid, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUstadz(ctx context.Context) ([]Ustadz, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateMasjid(ctx context.Context, arg UpdateMasjidParams) (Masjid, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUstadz(ctx context.Context, arg UpdateUstadzParams) (Ustadz, error)
}

var _ Querier = (*Queries)(nil)
